www.guapizuzhi.com: 127.0.0.1

m.guapizuzhi.com:
  protocol: http
  ip: 127.0.0.1
  port: 8000
  headers:
    =host: guapizuzhi.com
    +cookie: mock=1;
  path:
    /h5:
      protocol: https
      ip: 127.0.0.2
